melange-re/melange-re.github.io

docs/css/extra.css, docs/getting-started.md, docs/index.md, docs/learn.md, mkdocs.yml
Some initial structure:
- Landing page, with some features listed
- Top level navigation (Home, Getting Started, Learn)
Can be loaded locally with `mkdocs serve`. Otherwise, I made a deployment to https://melange-re.github.io/documentation-site/ (will set up GH action in a new PR).
Next, will continue with Getting Started in new PR.
=> add index page, some nav structure

docs/learn.md
Based on #4 (`learn/package-management`).
Adds a section about compilation model and Dune. Still draft as it's missing a paragraph or two that talk about runtime deps, which is a pretty critical feature imo.
The small "Dune manual" is inspired by Dune docs ["Quickstart" section](https://dune.readthedocs.io/en/stable/quick-start.html), but adapted to Melange, and without using `dune init` (which doesn't support Melange templates yet).
=> learn: build system

docs/communicate-with-javascript.md
Fixes #19.
Based on #32 (`comm-with-js/lang-concepts`).
Adds a subsection "Pipe operators" to the "Language concepts" section.
I decided to explain OCaml pipe operator, and then explain the limitations that led to the introduction of pipe first operator. I tried to avoid references to existing content besides the blog post I wrote, as all the issues and PRs that I could find are super confusing.
In general, it is quite hard to explain this in a way that makes sense, but hopefully it helps to have a reference that other places in the docs can point to. The PR already updates the links from the "Chaining" section.
=> comm with js: pipe operators

docs/communicate-with-javascript.md
Fixes #17.
Based on #32 (`comm-with-js/lang-concepts`).
I decided to mention the `unboxed` attribute as part of the "Language concepts" section that talks about attributes. Hopefully makes sense this way. I think it's a quite niche optimization that does not deserve its own section, and keeping it in the attributes section allowed to mention also other pre-built attrs like `alert` and `deprecated` that Melange programs can use as well.
=> comm with js: unboxed

mkdocs.yml, theme/main.html
adds a custom theme folder to mkdocs confic, so that we can customize `meta` tags:
https://www.mkdocs.org/user-guide/customizing-your-theme/
=> mkdocs: add meta tags

theme/versions.html
Fixes #45.
Replaces the `versions.html` fragment of the template, so that the GH link points to `melange-re/melange`. Based on [original readthedocs template](https://github.com/mkdocs/mkdocs/blob/562d5e14c1d2c914d42942ab2385822c04d5bc7b/mkdocs/themes/readthedocs/versions.html).
=> theme: add link to melange gh

docs/build-system.md
If the reader has been going through the example code and created an alias in the earlier section 'Using aliases', they need to build the project (in the 'Handling assets' section) using the alias `my-app`.
=> Fixed instructions on building app after an alias has been created

docs/communicate-with-javascript.md
clean up pipe first docs after @anmonteiro's comment in https://github.com/melange-re/melange-re.github.io/pull/33#discussion_r1204515775. (side note: the benefits of pipe first get more and more unclear to me over time...)
=> comm with js: pipe first tweaks

docs/build-system.md, docs/communicate-with-javascript.md
Fixes #18.
- Adds some docs about `module_systems` field in "Build system"
- Adds a section "Use Melange code from JavaScript" in "Comm with JS"
=> comm with js: add exports

.github/workflows/deploy.yml, .github/workflows/publish-version.yml, README.md, mkdocs.yml, pip-requirements.txt, theme/CNAME, theme/robots.txt
Fixes #47.
Uses [mike](https://github.com/jimporter/mike) to achieve so. The process is quite simple, `mike` handles folders for each version in the `gh-pages` branch.
- Pushes to `master` deploy to the `unstable` version
- A GH action is configured so that new tags with the `v*` format deploy a new version with the tag name, aliased to `stable`.
=> Publish versions

docs/melange-for-x-developers.md
Roadmap link pointed to the To Do page.  Now it points to the google docs share link.
=> Add link to roadmap

docs/rationale.md
I thought it might be a good idea to add a looking forward section to the rationale page, since it has that nice history recap.
The text is based off of anmonteiro's [post](https://discuss.ocaml.org/t/ann-melange-1-0-compile-ocaml-reasonml-to-javascript/12305#looking-forward-11) on OCaml discuss forum, plus a small summary of future goals from the roadmap.
(Of course, feel free to close if you don't think this section is necessary!)
=> Add looking forward section to rationale page

.github/workflows/deploy.yml, .gitignore, docs/api.md, docs/communicate-with-javascript.md, docs/melange-for-x-developers.md, mkdocs.yml
For now, only OCaml syntax is supported, but it should be easy to publish the docs with reason syntax too and adapt the links so that users are directed to the version of the docs with the syntax they chose, using this command:
```
ODOC_SYNTAX="re" opam reinstall melange
```
- Copy the html files generated by odoc from melange sources from the `.opam-switch` folder to the `docs` one, so that mkdocs can publish these files
- Link to the modules from the links in the markdown docs
- Fix a few other links
=> odoc: publish melange docs and link to them from the docs articles

.github/workflows/deploy.yml, .github/workflows/publish-version.yml, .gitignore, docs/api.md, docs/communicate-with-javascript.md
Continuation of #98.
Publishes the API docs for Melange in Reason syntax and updates all links to api modules and functions so that they go to the respective syntax page (`/api/ml` or `/api/re`).
Note the code blocks inside odoc chunks are not converted, see https://github.com/ocaml/odoc/issues/515. Might be something that we can add to odoc in the future.
cc @feihong
=> odoc: publish api docs in Reason syntax

.github/workflows/deploy.yml, .github/workflows/publish-version.yml, Makefile, docs/communicate-with-javascript.md, scripts/build-system.t, scripts/communicate-with-javascript.t, scripts/dune, scripts/extract_code_blocks.ml
Fixes #90.
The implemented tool `extract_code_blocks` takes a markdown file as input, reads the `ocaml` code snippets and creates a cram test `.t` with the snippets in it. This test file does not require any manual changes, it can be directly tested with dune.
To be able to compile any snippet, there is some functionality added to include "preludes" for each code snippet, for example, given this snippet
https://github.com/melange-re/melange-re.github.io/blob/c8506d8e78712d17bb872891ee183cec1ffe7ca1/docs/communicate-with-javascript.md?plain=1#L2790-L2792
We can add a prelude just before it to define `pet`:
https://github.com/melange-re/melange-re.github.io/blob/c8506d8e78712d17bb872891ee183cec1ffe7ca1/docs/communicate-with-javascript.md?plain=1#L2789-L2792
The `extract_code_blocks` tool …
=> extract code blocks

.github/workflows/deploy.yml, .github/workflows/publish-version.yml, Makefile, docs/build-system.md, docs/communicate-with-javascript.md, documentation-site.opam, scripts/build-system.t, scripts/communicate-with-javascript.t, scripts/extract_code_blocks.ml
Fixes #75.
Fixes #102.
- Updates switch to OCaml 5
- Updates melange, melange-playground, reason, and reason-react to latest
- Updates docs refs to `bs` -> `mel` or `u`
- Fix some of the tests
=> Latest Melange, OCaml 5, replace `@bs` with `@mel`

docs/communicate-with-javascript.md
I realized that there was a category called "Bind to global JavaScript functions or values" but the contents inside are not all related to global values, there are sections for modules, just plain functions etc. This PR rearranges the sections to hopefully make more sense.
=> bindings: rearrange global functions section

playground/src/app.jsx
The error markers were not showing on playground load because the `editorRef.current` was not assigned yet.
=> playground: fix onload error markers

.github/workflows/deploy.yml, pip-requirements.txt
Recent deploys [fail](https://github.com/melange-re/melange-re.github.io/actions/runs/6664631116/job/18112630832#step:18:23) with:
```
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.12.0/x64/bin/mike", line 5, in <module>
from mike.driver import main
File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/mike/driver.py", line 4, in <module>
from . import arguments, commands
File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/mike/commands.py", line 6, in <module>
from pkg_resources import resource_stream
ModuleNotFoundError: No module named 'pkg_resources'
```
It seems a patch was [applied](https://github.com/jimporter/mike/commit/063c93e9cce7c82939c7d47e6d33f99b24bba372) upstream, but a new version of mike hasn't been …
=> Fix mike error with pkg_resources

.github/workflows/deploy.yml, .github/workflows/publish-version.yml, Makefile, docs/build-system.md, docs/getting-started.md, docs/how-to-guides.md, docs/melange-for-x-developers.md, docs/package-management.md, documentation-site.opam, playground/src/app.jsx
Frst part of the Melange 2.2.0 docs release. Next part will be the long-standing branch + tag for proper release.
=> Prepare release OCaml 5.1.1, Melange 2.2.0

playground/vite.config.ts
There's a bug in rollup that prevents us to bundle the melange compiler and ocamlformat, see https://github.com/ocsigen/js_of_ocaml/issues/1547 and https://github.com/rollup/rollup/issues/5292.
For now disabling treeshaking, I briefly tried removing vite and use just esbuild but ran into a bunch of separate issues.
=> Remove rollup treeshake

docs/.vitepress/config.mts, docs/.vitepress/toggleSyntax.js
Currently, the scroll to location hash is broken due to vitepress doing the scroll before the `Switch.vue` component has had time to update the global classes that control the visibility of `reason` and `ocaml` blocks.
The PR adds a small script that mostly reproduces what `Switch.vue` is doing, but does so after `DOMContentLoaded` event, so when vitepress runs the scroll to hash logic, the content is already in its right position.
cc @feihong
=> fix scroll to location hash

docs/build-system.md, docs/getting-started.md, docs/how-to-guides.md, docs/package-management.md
Dune docs recently changed their layout breaking some existing links. Same with esy docs.
Broken links found using [Ahrefs Site Audit](https://ahrefs.com/site-audit).
=> Fix dune docs links

theme/versions.html
Usually offsite links open in a new tab.
If users want to navigate through the docs and also look at the Github page It is necessary to somehow copy the link or use a shortcut to open in other tab.
=> open github sidebar link on a separate tab

docs/.vitepress/config.mts, docs/.vitepress/dune.tmLanguage.json, docs/build-system.md, docs/communicate-with-javascript.md, docs/how-to-guides.md, docs/package-management.md
Issue: https://github.com/melange-re/melange-re.github.io/issues/6
=> Add syntax highlighting to dune snippets

README.md, docs/.vitepress/config.mts, docs/.vitepress/opam.tmLanguage.json, docs/how-to-guides.md, docs/package-management.md, playground/README.md
Addresses https://github.com/melange-re/melange-re.github.io/issues/6
=> Syntax highlighting for opam snippets

docs/.vitepress/config.mts, docs/.vitepress/ocaml.tmLanguage.json
The OCaml grammar file bundled with VitePress (via Shiki) is broken, it's unable to even highlight this snippet:
```ocaml
match foo with
| Some value -> doSomething value
| None -> error ()
```
We fix that by adding the grammar file used by the OCaml Platform VS Code plugin. Because VitePress's config API doesn't give you a way to override bundled grammars, we also have to add a hack that deletes the object with key "ocaml" from Shiki's `bundleLanguages` object.
=> Fix OCaml syntax highlighting

docs/communicate-with-javascript.md, scripts/communicate-with-javascript.t
@rusty-key suggested to include a "cookbook" section in the bindings page, so that users can grep for common JS patterns and map them to bindings.
This PR adds a cookbook at the end of "Communicate with JavaScript" page, based on https://github.com/yawaramin/bucklescript-bindings-cookbook.
=> Bindings cookbook

docs/.vitepress/config.mts, docs/getting-started.md, docs/syntaxes.md, package.json, yarn.lock
Addresses https://github.com/melange-re/melange-re.github.io/issues/38
=> Add Syntax page

docs/advanced-js-interop.md, docs/bindings-cookbook.md, docs/build-system.md, docs/data-types-and-runtime-rep.md, docs/dune, docs/language-concepts.md, docs/working-with-js-objects-and-values.md, scripts/advanced-js-interop.t, scripts/build-system.t, scripts/data-types-and-runtime-rep.t, scripts/dune, scripts/language-concepts.t, scripts/process_md.ml, scripts/working-with-js-objects-and-values.t
Also fix:
`process_md.ml` has been changed so that when it detects a snippet that begins with "val ", it assumes that it contains type signatures and wraps it with `module type _FAKE_  = sig ` and ` end`. After it converts to reason code, the extra lines are removed.
=> Fix code snippet compile errors

docs/advanced-js-interop.md, docs/attributes-and-extension-nodes.md, docs/bindings-cookbook.md, docs/data-types-and-runtime-rep.md, docs/melange-for-x-developers.md, docs/working-with-js-objects-and-values.md, scripts/working-with-js-objects-and-values.t
I fixed some typos and mistakes on the 'Working with JavaScript objects and values' page, and in the process converted all the JS output from commonjs to es6 (since I used Melange Playground to generate the snippets and all JS output there is es6 now).
Also in this PR:
=> Fix JS output in 'Working with JavaScript objects and values' page
