- flake.lock
- flake.nix
run with `nix develop -L .# -c mkdocs serve`
> chore: add flake.nix

- docs/package-management.md
Applies @anmonteiro's suggestions from https://github.com/melange-re/documentation-site/pull/4.
> package management: some rewrites

- docs/build-system.md
Applies @anmonteiro's suggestions from https://github.com/melange-re/documentation-site/pull/5.
> build system: rewrites

- docs/communicate-with-javascript.md
> comm with js: add docs for `bs.scope`

- docs/communicate-with-javascript.md
> comm with js: add docs for bs.re

- docs/getting-started.md
> [getting started]: add esy / nix sections

- docs/communicate-with-javascript.md
This PR reorganizes some of the content in "Communicate with JavaScript" page. It creates a new section "Language concepts" that is placed at the top of the page.
This new section serves two goals:
- Make the index of the page a bit cleaner, by grouping under a single section the content that is more about underlying concepts, and is not part of the "how-to guides" that come after
- Make room for the soon-to-be-written [pipe operator docs](#19), which will be included in this new "Language concept" section
For now, the structure of the new "Language concepts" section looks like:
- Attributes and extension nodes
- External functions (renamed from "Foreign function interface" for simplicity)
- Special identity external
- Abstract types
> comm with js: add "language concepts" section

- docs/melange-for-x-developers.md
- mkdocs.yml
> add "melange for x devs" section

- docs/build-system.md
> build system: update dune links

- docs/package-management.md
action item from https://github.com/melange-re/documentation-site/pull/27#issuecomment-1554452006
> package management: link to getting started

- .github/workflows/deploy.yml
> add gh action to deploy

- docs/build-system.md
> build system: fix opam installation instructions

- docs/communicate-with-javascript.md
> comm with js: fix raw explanation for reason syntax

- mkdocs.yml
Fixes #62.
https://github.com/mkdocs/mkdocs/issues/1783#issuecomment-486741030.
> fix sitemap

- docs/communicate-with-javascript.md
Please check to make sure I have done this correctly.
> Updated section 'Binding to callbacks' with ReasonML syntax.

- docs/community.md
> Add resources section

- docs/communicate-with-javascript.md
Changed bs.splice to bs.variadic and added note about bs.variadic replacing bs.splice.
> bs.splice to bs.variadic

- .github/workflows/deploy.yml
- README.md
- pip-requirements.txt
This will simplify installation and also track the versions we are using for the python deps.
> add pip-requirements.txt

- docs/build-system.md
> build system: remove pins to melange and dune

- docs/rationale.md
- docs/roadmap.md
- mkdocs.yml
See #81 and #82.
Just brainstorming some ideas about how the roadmap page could look.
> Add roadmap page

- .github/workflows/deploy.yml
- Makefile
- docs/communicate-with-javascript.md
> check reason syntax

- docs/how-to-guides.md
> "Migrate from v1 to v2" guide

- docs/package-management.md
Closes https://github.com/melange-re/melange-re.github.io/issues/86 and https://github.com/melange-re/melange-re.github.io/issues/79
> Rename to reason-react-ppx

- docs/package-management.md
Fixes #100.
I hesitated between adding it to the howtos section, but in the end I think the "Bindings and package management" section in the `package-management` page is the best place for it 🤔
> Add section about check-npm-deps

- docs/build-system.md
- docs/getting-started.md
- docs/melange-for-x-developers.md
- docs/package-management.md
@anmonteiro please take a look at the nix config to make sure i'm not messing up.
> update to ocaml 5.1

- documentation-site.opam
- playground/src/app.jsx
> Show warnings

- documentation-site.opam
- playground/src/app.jsx
Brings the improvement on melange-playground where alerts are returned in the warnings array.
> Playground: sync melange

- documentation-site.opam
- playground/src/app.jsx
- playground/src/examples.js
- playground/src/worker.js
Updates to latest unreleased versions of melange and reason-react. Brings the improvements on alerts handling generated by ppx done by @anmonteiro in [melange-re/melange#991](https://github.com/melange-re/melange/pull/991).
> Latest melange and reason-react

- docs/communicate-with-javascript.md
- scripts/communicate-with-javascript.t
> Abstract jsproperties

- playground/src/app.jsx
- playground/src/console.js
- playground/src/worker.js
Fixes https://github.com/melange-re/melange/issues/681.
> improve logs for runtime errors

- documentation-site.opam
Fixes #155 via https://github.com/melange-re/melange/pull/1021.
> Update to latest melange

- docs/community.md
> Fix resource link

- blog/posts/dune-universal-libraries-preview.md
adding a new blog post describing our path towards the solution we're experimenting with re: multi-context libraries
> new post: "Unlocking Universal Libraries in Dune"

- docs/getting-started.md
https://discuss.ocaml.org/t/suboptimal-getting-started-experience-with-melange/15185
> Remove create-melange-app

- Makefile
- docs/.vitepress/config.mts
- docs/community.md
- docs/resources.md
- package.json
https://github.com/melange-re/melange-re.github.io/issues/41
> Add Resources page

- docs/.vitepress/config.mts
This change makes top nav look like this:
> Add link to book in top nav

- README.md
- docs/resources.md
Also add some instructions for updating latest stable version docs
> Add talk videos to Resources page
